VERIFY_TOKEN = 'livechattest'
PAGE_ACCESS_TOKEN = 'EAAGQ9qpdwkgBAPPBSi7UOnpkGFXCyij3nF4ATZA1lT5vZCq6UaWsKPkMxZBPwQowxRVFXsU2tWiwLvNSh5lDQM6mnswZAOzHlKZAZAy12p5MP5ZB41B1gDdpJztZBRt0V7vMNPdXTueTtxZB72hlJZCR5g0qET9TuzjQ066o674Yey3RWC9SYF9fck'
MODEL_URI = "https://chatbotupdate-u2k5tzvaia-oc.a.run.app"
WEBSITE_URI = ""

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True
SQLALCHEMY_DATABASE_URI = "sqlite:///./db.sqlite"
